name: Trigger Complete (GET Proxy)

on:
  repository_dispatch:
    types: [complete_workout]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run completion
        run: echo "Triggered"
